version: '3'
services:
    postgres:
        image: postgres
        hostname: postgres
        restart: always
        environment: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST: postgres
        ports:
          - 5438:5432
        volumes:
          - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    
    app:
      build: ./app
      ports:
          - 5000:5000
      depends_on: 
        - postgres

volumes:
  pgdata:
 